//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("MenuItem")]
    public partial class MenuItem
    {
        [Key]
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public Nullable<int> MenuParentId { get; set; }
        public Nullable<bool> Active { get; set; }
        [NotMapped]
        public bool IsSelected { get; set; }
        [NotMapped]
        public virtual List<MenuItem> Children { get; set; }
    }
}

